irc:
    server: irc.freenode.net
    port: 6667
    ssl: false
    nick: irrawaddy
    channels:
        - "#dolphin-dev"
        - "#dolphin-test"
    trusted_users:
        - delroth

web:
    external_url: https://central.dolphin-emu.org
    bind: 127.0.0.1
    port: 8001

github:
    account:
        login: dolphin-emu-bot
        token: TOKEN
    maintain:
        - dolphin-emu/dolphin
    notify:
        - dolphin-emu/sadm
        - dolphin-emu/www
    trusted_users:
        group: dolphin-emu/trusted-developers
        refresh_interval: 300
    hook_hmac_secret: SECRET
    rebuild_command: "@dolphin-emu-bot rebuild"

gcode:
    atom_feed: https://code.google.com/feeds/p/dolphin-emu/issueupdates/basic
    refresh_interval: 10

buildbot:
    url: https://buildbot.dolphin-emu.org/
    jobdir: /home/buildbot/pr-jobdir
    pr_builders:
        - pr-android
        - pr-deb-x64
        - pr-osx-x64
        - pr-ubu-x64
        - pr-win-x64
        - pr-win-x86
